services:
  - type: web
    name: arcanum-core
    runtime: node
    rootDir: arcanum-core
    buildCommand: npm install
    startCommand: npm start
    plan: free
    region: oregon
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
